// Copyright (c) TotalSoft.
// This source code is licensed under the MIT license.

const fs = require('fs')
const path = require('path')

const appRoot = process.cwd()

const packageJsonUrl = path.resolve(`${appRoot}/package.json`)
const pjson = require(packageJsonUrl)

const content = `
// Copyright (c) TotalSoft.
// This source code is licensed under the MIT license.mitations under the License.

// this is autogenerated file, see scripts/version-update.js
export const VERSION = '${pjson.version}'
`

const fileUrl = path.join(appRoot, 'src', 'version.ts')

fs.writeFileSync(fileUrl, content)