# This workflow will run tests using node and then publish a package to NPM when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: run-tests

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main  

concurrency:
  group: build-test-publish

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build        
      - name: Run tests
        run: yarn test
